### ISSUE TITLE
GitLab CI cannot create GitHub release

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/rpm-spec-rnp#6]
https://gitlab.com/ribose/rpm-spec/rpm-spec-rnp/-/jobs/275757541

Changes have been made to [rpm-specs](https://github.com/riboseinc/rpm-specs/commit/584121b71172ce3b4e7ba3bfd80fb805392525ab) to allow the overriding of the "project namespace" parameter to the script `./create-github-release`.  Despite this update as well as the extra env var (`$PROJECT_NAMESPACE`) I added to GitLab CI/CD settings page, GitLab CI is still failing to create a GitHub release.

I suspect it's due to the fact that @ribose-ci is not part of [any team](https://github.com/orgs/rnpgp/teams) of new rnpgp organization.  @ribose-ci has already been invited but I can't make it accept the invitation.

**Comment by ronaldtse** [comment]
@ribose-jeffreylau @ribose-ci has now accepted the invitation. Anything else I need to do?

**Comment by ribose-jeffreylau** [comment]
Should be fine now.  Thanks.
The original "NOT FOUND" error has [turned into an `already_exists` error](https://gitlab.com/ribose/rpm-spec/rpm-spec-rnp/-/jobs/275841942).
