### ISSUE TITLE
Setup secrets for RPM release

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rpm-spec-rnp#8]
@ribose-jeffreylau could you help setup these secrets (org-wide):
* `PACKAGE_SIGNING_KEY_BASE64` 
* `GITHUB_YUM_DEPLOY_KEY_BASE64`

Thanks!

_Originally posted by @ronaldtse in https://github.com/rnpgp/rpm-spec-rnp/issues/7#issuecomment-629576614_

**Comment by ribose-jeffreylau** [comment]
The following org-wide action secrets have been set up:

- `PACKAGE_SIGNING_KEY_BASE64`
- `GHUB_YUM_DEPLOY_KEY_BASE64`
  - The name `GITHUB_YUM_DEPLOY_KEY_BASE64` is not allowed to be used, apparently.
